name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, sqlite3, xml, curl, mysql

    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server

    - name: Start MySQL server
      run: |
        sudo service mysql start

    - name: Update MySQL root user password
      run: |
        sudo mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"

    - name: Create database
      run: |
        mysql -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS task_management;"

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Configure Laravel cache
      run: php artisan config:cache

    - name: Run migrations and seed database
      run: php artisan migrate --seed

    - name: Run tests
      run: php artisan test --log-junit results.xml
      continue-on-error: true

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.xml
