name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, bcmath
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Create database
        run: |
          sudo apt-get install -y mysql-server
          sudo service mysql start
          mysql -e 'CREATE DATABASE task_management;'

      - name: Configure Laravel database
        run: php artisan config:cache

      - name: Run migrations
        run: php artisan migrate

      - name: Seed database
        run: |
          php artisan db:seed --class=UsersTableSeeder
          php artisan db:seed --class=AdminsTableSeeder

      - name: Run tests
        run: php artisan test
